### ISSUE TITLE
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 23.0 which is incompatible.

### ISSUE THREAD

**Issue by sdlkhfksl** [yym68686/ChatGPT-Telegram-Bot#11]
这个怎么解决

**Comment by sdlkhfksl** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.11 requires packaging<21.0,>=20.4, but you have packaging 22.0 which is incompatible.

**Comment by sdlkhfksl** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pytoolconfig 1.2.4 requires packaging>=22.0, but you have packaging 20.9 which is incompatible.

**Comment by yym68686** [comment]
试试

```bash
pip install --upgrade packaging
```

**Comment by sdlkhfksl** [comment]
> 试试
> 
> ```shell
> pip install --upgrade packaging
> ```

**Comment by sdlkhfksl** [comment]
pip install -r requirements.txt --no-dependencies

**Comment by sdlkhfksl** [comment]
pip install --upgrade poetry
pip install clikit==0.4.1
pip install crashtest==0.4.1
