### ISSUE TITLE
No such file: main.py repl process died unexpectedly: exit status 2

### ISSUE THREAD

**Issue by ly-img** [yym68686/ChatGPT-Telegram-Bot#16]
点run
No such file: main.py
repl process died unexpectedly: exit status 2
![image](https://user-images.githubusercontent.com/128985777/229132701-6dd06cd6-81df-4e40-8262-705eff71eb75.png)

**Comment by ly-img** [comment]
复制webhool.py内容到新建的main.py run是这样
![image](https://user-images.githubusercontent.com/128985777/229136683-233e9069-68cd-4694-94f3-e7de60d9c288.png)

**Comment by ly-img** [comment]
请大佬修改后测试一下 谢谢

**Comment by yym68686** [comment]
开发时间有限，已经加入到待实现的功能列表里面了。如果有能力的话欢迎 pr 👏。

**Comment by mewchore** [comment]
The environment variables for WEB_HOOK, BOT_TOKEN & COOKIES should be retrieved by the method os.getenv("WEB_HOOK") to work on Replit. I don't know why the current way does not work though.

**Comment by mewchore** [comment]
The `entrypoint` in the `.replit` file should also be changed to `./webhook.py` then the run button works.

**Comment by yym68686** [comment]
> The environment variables for `WEB_HOOK`, `BOT_TOKEN` & `COOKIES` in `config.py` should be retrieved by the method os.getenv("WEB_HOOK") to work on Replit. I don't know why the current way does not work though.

Maybe you filled in the wrong webhook value, what did you fill in?

**Comment by yym68686** [comment]
> 请问有黑白名单模式吗

现在支持白名单了，具体设置方法可以参照 README。
