### ISSUE TITLE
Im having this issue 

### ISSUE THREAD

**Issue by rokipet** [yym68686/ChatGPT-Telegram-Bot#32]
WARNING - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='Caky', id=1601378566, type=<ChatType.PRIVATE>, username='Perolatero'), date=datetime.datetime(2024, 3, 6, 17, 32, 35, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=5, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='Caky', id=1601378566, is_bot=False, language_code='en', username='Perolatero'), group_chat_created=False, message_id=31, supergroup_chat_created=False, text='/info'), update_id=872570166)" caused error "'in <string>' requires string as left operand, not int"

**Comment by yym68686** [comment]
Do you still have this issue now? You can try redeploying.
