### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by dubr1k** [yym68686/ChatGPT-Telegram-Bot#35]
Hi! Please tell me what needs to be changed so that the bot is in English and responds in English?

**Comment by yym68686** [comment]
After using the `/info` command, you can switch the language of the robot's responses between Chinese and English by clicking the flag button in the middle of the first line of the display panel. However, currently, switching the text above the button to English is not supported. This part will be supported by me later. If you have time, you are also welcome to contribute to this project.

**Comment by yym68686** [comment]
Now, the button text displayed by default after the robot is deployed is in English, and the response language is also set to English by default. You just need to redeploy.
