### ISSUE TITLE
Feat Req: setting and switching system messages via bot's commands

### ISSUE THREAD

**Issue by Lavanille777** [yym68686/ChatGPT-Telegram-Bot#36]

**Comment by yym68686** [comment]
Okay, I will implement this feature.

**Comment by Lavanille777** [comment]
> Okay, I will implement this feature.

really appreciate it

**Comment by yym68686** [comment]
Now, you can customize the system prompt while resetting the bot by using `/reset+system prompt`. `/reset` can still be used alone.
