### ISSUE TITLE
[feature request] support Google Vertex AI

### ISSUE THREAD

**Issue by krau** [yym68686/ChatGPT-Telegram-Bot#38]
Google Vertex AI API needs to be called with two parameters: project_id and location.

Reference documentation: 

https://cloud.google.com/vertex-ai/generative-ai/docs/start/quickstarts/quickstart-multimodal?hl=zh-CN

thanks for your work =￣ω￣=

**Comment by yym68686** [comment]
I did not use the Vertex AI API, the endpoint I used is https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent, so there is no need to pass in the two parameters: project_id and location. May I ask if you have a scenario where you must use the Vertex AI API?

**Comment by krau** [comment]
> I did not use the Vertex AI API, the endpoint I used is https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent, so there is no need to pass in the two parameters: project_id and location. May I ask if you have a scenario where you must use the Vertex AI API?

Vertex AI provides more professional service support for businesses, but individual users do not need it.
So you are right, this repo does not need to support Vertex AI, and there is no difference in accessing Gemini between using Google API and Vertex AI.
