### ISSUE TITLE
[FR] Optional conversation summarisation and timed chat reset

### ISSUE THREAD

**Issue by afafara** [yym68686/ChatGPT-Telegram-Bot#40]
I would like to request two optional env-var flags:
`MAX_HISTORY_SIZE=N` - where N is number of messages after which conversation is summarised (to avoid too many tokens being used). If unset, it's unlimited. If set to 0, that means conversation is reset after each message
`MAX_CONVERSATION_AGE=N` - where N is time in minutes after which the conversation is automatically reset. If unset, it's unlimited. If set to 0, that means conversation is reset after each message

Example scenarios where it could be useful:
max history - avoiding excessive token usage for long conversations (where often summarisation is enough)
max conv age - using bot sporadically (like once, twice a day), without needing to remember to reset; bot acting as bi-lingual translator (with static prompt), with each message not connected at all to the previous one

**Comment by yym68686** [comment]
Hello, I have updated a new feature, now support using the RESET_TIME environment variable to automatically reset the chat history of all users except the admin list every RESET_TIME seconds.
