### ISSUE TITLE
[FR] Use custom Anthropic API url

### ISSUE THREAD

**Issue by delfer** [yym68686/ChatGPT-Telegram-Bot#43]
Hello @yym68686 ! You made a very very good Telegram bot! Thank you! I use my own LLM proxy on LiteLLM with supports Anthropic API. Can you please add option to change Anthropic API address?

**Comment by SHLE1** [comment]
You can use environment variable CLAUDE_API_URL to customize Claude API base URL

**Comment by delfer** [comment]
It works! Thank you!
