### ISSUE TITLE
About PASS_HISTORY

### ISSUE THREAD

**Issue by snakeying** [yym68686/ChatGPT-Telegram-Bot#44]
在开启了PASS_HISTORY后，如何重新开始一个话题？我在代码中没有找到类似/newtopic或者/clearhistory的命令。

请问能否考虑添加？

After enabling PASS_HISTORY, how do I start a new topic? I haven't found any commands like /newtopic or /clearhistory in the code.

Could you consider adding them?

**Comment by yym68686** [comment]
使用 `/reset` 命令即可。

**Comment by snakeying** [comment]
嗯嗯嗯，我在您提供的bot中找到了这个命令。我只是觉得是否会引起误解，毕竟有些人会认为reset是重新设置的意思

**Comment by yym68686** [comment]
reset命令可以设置系统提示，不能重置设置，只能重置对话。如果有词能准确表达这三种意思，我将采纳你的单词。确实会有歧义，但我想不到更好的词语。😂

**Comment by snakeying** [comment]
啊哈，抱歉，并不是鸡蛋里面挑骨头，我只是担心有些歧义。

PS：我看了一下config，是支持system prompt的，请问可以添加到environment variables中吗？

**Comment by yym68686** [comment]
没关系，目前支持通过环境变量 SYSTEMPROMPT 自定义系统提示。后面有时间放进README里面。

**Comment by snakeying** [comment]
感谢
