### ISSUE TITLE
[bug] Groq API 呼叫異常

### ISSUE THREAD

**Issue by Lawlietr** [yym68686/ChatGPT-Telegram-Bot#48]
無法正常呼叫 Groq API
Gemini API 可正常呼叫

我的 docker-compose.yaml:
> version: "3.5"
> services:
>   chatgptbot:
>     container_name: chatgptbot
>     image: yym68686/chatgpt:latest
>     environment:
>       - BOT_TOKEN=ＭyBotToken
>       - GROQ_API_KEY=My_GROQ_API_KEY
>       - GOOGLE_AI_API_KEY=My_GOOGLE_AI_API_KEY
>       - whitelist=MyID
>       - ADMIN_LIST=MyID
>       - CUSTOM_MODELS=-gpt-4o,-claude-3-5-sonnet
>       - temperature=0.7

log:
> chatgptbot  | 2024-08-09 01:59:56,442 - root - WARNING - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='lawliet', id=Myid567, type=<ChatType.PRIVATE>, username='lawlietr'), date=datetime.datetime(2024, 8, 9, 1, 59, 56, tzinfo=<UTC>), delete_chat_photo=False, from_user=User(first_name='lawliet', id=Myid567, is_bot=False, language_code='zh-hant', username='lawlietr'), group_chat_created=False, message_id=109, supergroup_chat_created=False, text='hello'), update_id=myupdateid)" caused error "local variable 'role' referenced before assignment"
> chatgptbot  | 2024-08-09 01:59:56,446 - root - WARNING - Error traceback: Traceback (most recent call last):
> chatgptbot  |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1148, in __create_task_callback
> chatgptbot  |     return await coroutine  # type: ignore[misc]
> chatgptbot  |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
> chatgptbot  |     return await self.callback(update, context)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 100, in wrapper
> chatgptbot  |     return await func(*args, **kwargs)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 38, in wrapper
> chatgptbot  |     return await func(*args, **kwargs)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 29, in wrapper
> chatgptbot  |     return await func(*args, **kwargs)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 78, in wrapper
> chatgptbot  |     robot, role = get_robot(convo_id)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/config.py", line 279, in get_robot
> chatgptbot  |     return robot, role
> chatgptbot  | UnboundLocalError: local variable 'role' referenced before assignment
> chatgptbot  | 
> chatgptbot  | 2024-08-09 02:01:34,498 - root - WARNING - Update "Update(message=Message(channel_chat_created=False, chat=Chat(first_name='lawliet', id=Myid567, type=<ChatType.PRIVATE>, username='lawlietr'), date=datetime.datetime(2024, 8, 9, 2, 1, 34, tzinfo=<UTC>), delete_chat_photo=False, entities=(MessageEntity(length=5, offset=0, type=<MessageEntityType.BOT_COMMAND>),), from_user=User(first_name='lawliet', id=Myid567, is_bot=False, language_code='zh-hant', username='lawlietr'), group_chat_created=False, message_id=110, supergroup_chat_created=False, text='/info'), update_id=myupdateid)" caused error "local variable 'role' referenced before assignment"
> chatgptbot  | 2024-08-09 02:01:34,499 - root - WARNING - Error traceback: Traceback (most recent call last):
> chatgptbot  |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1264, in process_update
> chatgptbot  |     await coroutine
> chatgptbot  |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
> chatgptbot  |     return await self.callback(update, context)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 61, in wrapper
> chatgptbot  |     return await func(*args, **kwargs)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 38, in wrapper
> chatgptbot  |     return await func(*args, **kwargs)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/utils/decorators.py", line 29, in wrapper
> chatgptbot  |     return await func(*args, **kwargs)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/bot.py", line 550, in info
> chatgptbot  |     info_message = update_info_message(convo_id)
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/config.py", line 230, in update_info_message
> chatgptbot  |     f"**🚰 Tokens usage:** `{get_robot(user_id)[0].tokens_usage[str(user_id)]}`\n\n" if get_robot(user_id)[0] else "",
> chatgptbot  |   File "/home/ChatGPT-Telegram-Bot/config.py", line 279, in get_robot
> chatgptbot  |     return robot, role
> chatgptbot  | UnboundLocalError: local variable 'role' referenced before assignment

**Comment by yym68686** [comment]
感谢提供报错日志。我已经修复了这个 bug，你可以重新部署试试。
