### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by spiderpanel** [yym68686/ChatGPT-Telegram-Bot#53]
Hi,

need to upload documents files, including large ones, and often require assistance with tasks such as summarizing a book in PDF format. However, there is a limit of 2048 characters per message on Telegram.

To address this, we need an internal converter capable of processing various document and application files, such as .py, .doc, .js , and more, converting them into text format.

Thank you.

**Comment by yym68686** [comment]
Hello, the file upload feature has been supported for a long time.

**Comment by yym68686** [comment]
<img width="889" alt="image" src="https://github.com/user-attachments/assets/480f74d0-481d-41ca-b77a-4af8300d7039">


I have successfully obtained the file content here, you need to change the question. o1-preview has relatively high security.

**Comment by spiderpanel** [comment]
<img width="157" alt="image" src="https://github.com/user-attachments/assets/15e9128d-86a1-4ae3-89cb-0e8bd4ec7e4a">

no any problem with 4o turbo and mini,  everything was fine. but o1 takes too long time and not answering at all, i am refreshing my usage from openai , showing deducted price from my account but i did not received answer

<img width="536" alt="image" src="https://github.com/user-attachments/assets/fe7b7729-459f-46ca-a0db-2a08e4eb1b0f">



13 minute thinking, deducting price , but no any answer at all
