### ISSUE TITLE
建议支持Markdown格式

### ISSUE THREAD

**Issue by Silentely** [yym68686/ChatGPT-Telegram-Bot#54]
图1是使用本项目搭建的，在询问ai关于计算或者代码时的回复，回复的内容表达形式不够直观
![e2ac8a56358e12cd3516e314664c79da.jpeg](https://ice.frostsky.com/2024/09/26/e2ac8a56358e12cd3516e314664c79da.jpeg)
    
图2是使用Markdown的回复
![0e8f545d3946bde649c1279d730eb4fa.jpeg](https://ice.frostsky.com/2024/09/26/0e8f545d3946bde649c1279d730eb4fa.jpeg)

建议大佬在本项目增加Markdown格式内容支持

**Comment by yym68686** [comment]
可以把问题发一下，后面我针对性适配一下。

**Comment by Silentely** [comment]
> 可以把问题发一下，后面我针对性适配一下。

假设一辆车可以在 3.85s 的时间内从 0 加速到 27.8 m/s，请计算这辆车的加速度，单位为 m/s/s

**Comment by yym68686** [comment]
你好，现在已经支持了，这是现在的效果：

<img width="375" alt="image" src="https://github.com/user-attachments/assets/2d5fdba1-b676-4f0e-9d89-c05cf1d9dc74">
