### ISSUE TITLE
Using Gpt-4o but charged for GPT-4-0613

### ISSUE THREAD

**Issue by folis** [yym68686/ChatGPT-Telegram-Bot#60]
Hi, I've been using Gpt-4o which is sen in preferenses. But, according to my billing in Open-AI, I was using GPT-4-0613. Am I'm doing something wrong?

**Comment by yym68686** [comment]
Hello, please send the complete bot log to me for analysis.

**Comment by folis** [comment]
Is this a bot log? I see only whole conversation host6ory, model seems to be chosen corretly "gpt-4o" and "gpt-4-mini" as was specified in preferences

docker logs -f chatbot > chatbot_logs.txt

**Comment by yym68686** [comment]
The file chatbot_logs.txt is the bot's log, upload this file for me to check.

**Comment by yym68686** [comment]
Hello, without any logs for me to check, I will not be able to determine how to fix this bug. If no log files are provided after one day, I will consider this issue resolved and will close the issue at that time.

**Comment by folis** [comment]
Thank you for amazingly fast reply. The issue was in API used in other project. Sorry to bother

**Comment by folis** [comment]
Resolved
