### ISSUE TITLE
/reset or chat_history not work

### ISSUE THREAD

**Issue by ratu-sh** [yym68686/ChatGPT-Telegram-Bot#62]
when check or uncheck "chat history" parameter in settings - chatbot not clear its context by /reset command - even after clearing chat in Telegram - it still answers with previous context in mind. only thing that really clears chatbot context - is restarting python on server side.

if it is not a bug, than what purpose of /reset button? maybe you can add command /clear - to clear context of bot to start new conversation without old chatings?

**Comment by yym68686** [comment]
Hello, please paste the operation process log that can describe the bug. For example: I selected the chat history, copied the question log, and continued to ask the bot for the backend log after resetting. Also, provide all environment variable settings.

**Comment by yym68686** [comment]
Hello, could you provide more information to help me fix the bug? If no further information is provided, this issue will be considered resolved and will be closed tomorrow.
