### ISSUE TITLE
bot send URL instead of PICTURE to telegram chat

### ISSUE THREAD

**Issue by ratu-sh** [yym68686/ChatGPT-Telegram-Bot#65]
when using drawing models from `gpt-god` or `AImlAPI` provider, bot not send picture in chat but send URL with picture.
I think it can be parsed and added like photo to telegram chat

```
ME, [07.11.2024 14:52]
draw a cat

AI, [07.11.2024 14:52]
🤖️ gpt-4o

{"prompt": "A cute, realistic cat sitting calmly with a soft, fluffy fur coat. The cat has big, expressive eyes and slightly pointed ears, sitting in a relaxed posture, facing forward. Its fur is light gray with subtle darker stripes. The background is simple and light, focusing attention on the cat itself. Detailed, realistic rendering with warm and gentle tones.", "size": "1024x1024"}

image1 (https://filesystem.site/cdn/20241107/LVLb2JH9AbMwngknKI9VVXNoq05EAa.webp)

下载1 (https://filesystem.site/cdn/download/20241107/LVLb2JH9AbMwngknKI9VVXNoq05EAa.webp)

```

**Comment by ratu-sh** [comment]
providers link

https://gptgod.online/

https://aimlapi.com/app/

**Comment by yym68686** [comment]
Hello, Dalle-3 of the bot is called through the tools function. In the case where the API already has a built-in drawing function, the bot cannot output images separately. Please use an API that supports tools.

**Comment by ratu-sh** [comment]
is it impossible to implement such logic: parse bot's answers before sending it to telegram chat and if it contains any pictures link (like JPG, JPEG, PNG, GIF, WEBP and so on) - then send it via telegram API with methods `sendPhoto` ? maybe even convert to supported image format before sending... and shrinking to 10MB if it has larger size...

**Comment by yym68686** [comment]
I have fixed this bug.

**Comment by ratu-sh** [comment]
still not send image, still send URL
```
MEㅤ, [07.11.2024 21:05]
draw a cat

AI, [07.11.2024 21:05]
{"prompt": "A cute, realistic drawing of a cat sitting and looking curious. The cat has soft fur with a mix of light gray and white colors, with big, expressive eyes, and small whiskers. The background is simple, light-colored, and unobtrusive to focus on the cat. The cat is in a relaxed position with its tail wrapped around its paws, giving a calm and friendly appearance.", "size": "1024x1024"}

image1 (https://filesystem.site/cdn/20241108/GHLsxBAJNidSekOO4aYu8ksHeiwmr7.webp)

下载1 (https://filesystem.site/cdn/download/20241108/GHLsxBAJNidSekOO4aYu8ksHeiwmr7.webp)

Here image of cat!
```

**Comment by ratu-sh** [comment]
```
2024-11-07 18:05:13,090 - uni-api - INFO - provider: gpt-god     model: gpt-4o                 engine: gpt
INFO:     10.60.0.2:60048 - "POST /v1/chat/completions HTTP/1.1" 200 OK
```

**Comment by yym68686** [comment]
> still not send image, still send URL
> 
> ```
> MEㅤ, [07.11.2024 21:05]
> draw a cat
> 
> AI, [07.11.2024 21:05]
> {"prompt": "A cute, realistic drawing of a cat sitting and looking curious. The cat has soft fur with a mix of light gray and white colors, with big, expressive eyes, and small whiskers. The background is simple, light-colored, and unobtrusive to focus on the cat. The cat is in a relaxed position with its tail wrapped around its paws, giving a calm and friendly appearance.", "size": "1024x1024"}
> 
> image1 (https://filesystem.site/cdn/20241108/GHLsxBAJNidSekOO4aYu8ksHeiwmr7.webp)
> 
> 下载1 (https://filesystem.site/cdn/download/20241108/GHLsxBAJNidSekOO4aYu8ksHeiwmr7.webp)
> 
> Here image of cat!
> ```

I have fixed this bug.

**Comment by ratu-sh** [comment]
yes. now it works! thanks!
