### ISSUE TITLE
Tg-bot can’t parse image link from flux chatbot

### ISSUE THREAD

**Issue by ratu-sh** [yym68686/ChatGPT-Telegram-Bot#67]
>>GitHub, [08.11.2024 22:26]
🔨 1 new commit (https://github.com/yym68686/ChatGPT-Telegram-Bot/compare/ae0af7cf42e4...a6647cc571f1) to ChatGPT-Telegram-Bot:main:

>>a6647cc (https://github.com/yym68686/ChatGPT-Telegram-Bot/commit/a6647cc571f19451bfe9d5a8ea6c312042807d57): 🐛 Bug: Fix the bug that prevents extracting image URLs with parameters. by yym68686

>>GitHub, [08.11.2024 22:29]
🔨 1 new commit (https://github.com/yym68686/ChatGPT-Telegram-Bot/compare/a6647cc571f1...275a0c663152) to ChatGPT-Telegram-Bot:main:

>>275a0c6 (https://github.com/yym68686/ChatGPT-Telegram-Bot/commit/275a0c66315217f35c40ca063d0553bb77866cfd): 🐛 Bug: Bug of resending after the image has already been sent. by yym68686

before this update `flux` model generate images very good but duplicates pictures.

now it stop work

before

---

ME, [08.11.2024 14:57]
Нарисуй кошку

AI, [08.11.2024 14:58]
![image](https://github.com/user-attachments/assets/2c28eb23-f0c8-4409-87e4-896a063769e6)

AI, [08.11.2024 14:58]
🤖️ flux

{
  "prompt": "A cute cat sitting on a sunny windowsill, sun rays shining through the glass, a playful expression on its face, with fluffy fur and bright green eyes.",
  "height": 512,
  "width": 512
}

 生成中✅

https://filesystem.site/cdn/20241108/VOErf9nG6cIJi7p2mW8qJeRxbELI2o.jpg
![image](https://github.com/user-attachments/assets/1bf6fa89-be56-4b7e-8372-45d7d5b2bbf3)

---

after

---

ME , [08.11.2024 23:28]
draw a cat

AI, [08.11.2024 23:28]
🤖️ flux

{
  "prompt": "A cute, fluffy cat sitting gracefully on a sunny windowsill, with bright green eyes and a soft, pastel-colored fur. The background is a cozy room decorated with houseplants and soft pillows.",
  "height": 1440,
  "width": 1440
}

 生成中

 生成中

 生成中生成失败: 当前模型负载较高，请稍候重试，或者切换其他模型
Reason:

undefined

**Comment by yym68686** [comment]
The reason based on the information you provided is that the image generation API is unstable, so please switch to another stable text-to-image API. If the new API still cannot send images, it is a bug with the bot; otherwise, it is not a bug.

**Comment by ratu-sh** [comment]
Yes, it was maintenance time from provider.
They change image link that chatbot gives you.

now bot can’t parse this type of links

🤖️ flux

{
  "prompt": "A cute fluffy cat sitting on a windowsill, looking outside with bright green eyes, sunlight streaming in, surrounded by potted plants and a colorful cityscape in the background.",
  "height": 512,
  "width": 512
}


 生成中✅

https://pfst.cf2.poecdn.net/base/image/7fe4e48a4213e54a893e10aee94dd554942b21d27fd9fab40058cea8088ac5a7?w=1024&h=768&pmaid=200986697

**Comment by ratu-sh** [comment]
Image is not sent. Only url

**Comment by ratu-sh** [comment]
Not it works and parse this type of link

**Comment by yym68686** [comment]
I have fixed this bug.

**Comment by chelaxian** [comment]
Bot not parse output again because on no extension. Should auto add .jpg in the end of link:

🤖️ flux

{
  "prompt": "A plump cat with a belly sitting on a couch, wearing a dirty t-shirt and sweatpants, holding a TV remote and a can of beer in its paws.",
  "aspect_ratio": "16:9",
  "num_inference_steps": 30
}


 生成中...✅

https://filesystem.site/cdn/20250124/MiA86kPqC0MGKht2HVCBAKlkT7JgXv

**Comment by chelaxian** [comment]
or can you say which file should i modify - i will do it by myself.

**Comment by chelaxian** [comment]
i think the problem is here

https://github.com/yym68686/ChatGPT-Telegram-Bot/blob/e29d33c43c38221d1752f0a15f2a0fa085cb3b76/bot.py#L418

`bot.py` should parse also links without extentions, temporary download it to `temp_folder`, add `.jpg` extension, send in chat and delete from `temp_folder`

**Comment by yym68686** [comment]
Yes, I think this problem is difficult to solve because most image URLs end with extensions. I don't want URLs without extensions to be parsed as images. Therefore, this problem cannot be resolved. You should suggest the API provider replace URLs with URLs that end with extensions.

**Comment by chelaxian** [comment]
> Yes, I think this problem is difficult to solve because most image URLs end with extensions. I don't want URLs without extensions to be parsed as images. Therefore, this problem cannot be resolved. You should suggest the API provider replace URLs with URLs that end with extensions.

Ok, then I will try to fix it locally without PR. Can you approve that I find right place to fix code?

**Comment by yym68686** [comment]
Yes, you found the correct code location.

**Comment by chelaxian** [comment]
also i have an idea how to solve it but it is not actual now because `gptgod` change link again and now it has extension, but anyway just for history - we can fix `no extension` error by this service (also can be selfhosted too) - wsrv.nl

just rewriting URL from something like 
`https://URL`
to
`https://wsrv.nl/?url=[URL_encoded]&output=jpg`
fixes the problem

---

example:
before
`https://filesystem.site/cdn/20250303/k04esFbjh490T032WOqWFHNTGwjbOO`
after
`https://wsrv.nl/?url=https%3A%2F%2Ffilesystem.site%2Fcdn%2F20250303%2Fk04esFbjh490T032WOqWFHNTGwjbOO&output=jpg
`
