### ISSUE TITLE
FR: Auto-Folding Message & Source Citation for Search

### ISSUE THREAD

**Issue by omegaduncan** [yym68686/ChatGPT-Telegram-Bot#69]
**1. Message Auto-Folding:**

Currently, the bot's responses, especially in busy group chats, can be quite lengthy and disruptive. This feature requests an auto-folding option for bot messages to mitigate this issue.

* **User-Configurable Options:**
    * **Always Fold:** Fold every bot message regardless of length.
    * **Fold if Long:** Fold messages exceeding a user-definable character limit. A suggested default limit could be Telegram's message preview length, or a customizable value in the bot's `/info` settings. This allows users to tailor the folding behavior to their specific needs and group chat environments.

This would significantly improve the user experience in group chats by minimizing clutter and allowing users to expand messages only when needed.

**2. Source Citation for Search Results:**

When the bot utilizes the search functionality (DuckDuckGo or Google), it would be beneficial to include the source URL(s) of the information retrieved. This enhances transparency and allows users to verify the information's origin and explore the context further.

This could be implemented by appending the relevant URL(s) at the end of the bot's response, perhaps using a consistent format like:

```
Source(s): [link1], [link2], etc.
```

This relatively simple addition would greatly improve the reliability and academic integrity of the bot's responses.

**Comment by yym68686** [comment]
Source URL citation feature has been implemented. Text folding functionality is not considered for now.
