### ISSUE TITLE
The bot's response is duplicated when the o1-preview model is selected

### ISSUE THREAD

**Issue by ergashev** [yym68686/ChatGPT-Telegram-Bot#70]
The telegram bot's response is duplicated when the request and the openai response are large. The bot's responses are not duplicated on short queries. A more accurate scenario has not yet been reproduced.

**Comment by yym68686** [comment]
Hi, I have added a new feature to the bot: support for streaming output of the o1 model. Please redeploy the bot to check if your bug has been resolved.

**Comment by yym68686** [comment]
Hello, if no additional information is provided, this issue will be considered resolved. If you have any other questions, feel free to leave a message.
